plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      published_at: "2018-03-11"
      updated_at: "2018-03-11"

exclude:
    - "*.config.js"
    - "package*.json"
    - assets
    - node_modules
    - _data/manifest.yml
    - "Gemfile*"
    - "update-*.php"
    - CNAME
